### ISSUE TITLE
Leverage Skill in in Tier 3 of TaskMaster Causes crashes on Master and Experimental Builds 

### ISSUE THREAD

**Issue by knighto95** [Crackdown-PD2/deathvox#145]
[crash.txt](https://github.com/Crackdown-PD2/deathvox/files/8429981/crash.txt)
[crashlog.txt](https://github.com/Crackdown-PD2/deathvox/files/8429986/crashlog.txt)

**Comment by offyerrocker** [comment]
Fixed as of https://github.com/Crackdown-PD2/deathvox/commit/9519890589072e4e74706071ed8e98a8d8868af3
