### ISSUE TITLE
Only Crash

### ISSUE THREAD

**Issue by Kcalb070** [Crackdown-PD2/deathvox#147]
I tried to play the mod but it Crashes completely, I did a completely clean install, reinstall the game just to play the mod and it Crashes anyway, I leave the Crashlog below, but most likely the mod requires an update for the latest patch of the game
note: i traid with the 2 versions Experimental and Master
Application has crashed: C++ exception
[string "lib/managers/group_ai_states/groupaistatebesi..."]:4381: bad argument #1 to 'ipairs' (table expected, got nil)

SCRIPT STACK

create_timed_groups_table() lib/managers/group_ai_states/groupaistatebesiege.lua:4381
_init_misc_data() lib/managers/group_ai_states/groupaistatebesiege.lua:42
init() lib/managers/group_ai_states/groupaistatebase.lua:147
init() @mods/deathvox-experimental/lua/lib/managers/group_ai_states/groupaistatebesiege.lua:27
new() core/lib/utils/coreclass.lua:35
set_state() lib/managers/groupaimanager.lua:41
_load_ai_settings() core/lib/utils/dev/editor/coreworlddefinition.lua:589
create() core/lib/utils/dev/editor/coreworlddefinition.lua:416
create_world() core/lib/utils/dev/editor/worldholder.lua:110
init_game() lib/setups/gamesetup.lua:715
core/lib/setups/coresetup.lua:422

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                   steamclient  (???)     Steam_TerminateGameConnection                       
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.128.129
	CPU : AMD Ryzen 5 5600H with Radeon Graphics (6 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1
	DirectX : 12.0 
	GPU : NVIDIA GeForce RTX 3050 Laptop GPU / nvldumd.dll[31.0.15.1694]
	Language : spanish
	Memory :     5996MB 68KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Auriculares (Realtek(R) Audio))

**Comment by offyerrocker** [comment]
Thanks for the report!
This should be resolved as of commit c7265ab1283da7656740b88eac3b8f2a2133af2a.
