### ISSUE TITLE
Goodwill Hunting Aced crash in arrowbase

### ISSUE THREAD

**Issue by GenesisEB** [Crackdown-PD2/deathvox#149]
Ghost -> Assassin -> Goodwill Hunting Aced causes a crash when getting a headshot on any enemy with the pistol crossbow.
Experimental Branch gives CTD's on map load.

**Mods:**
SuperBLT
BeardLib
deathvox-master (also tried cracksgiving release and experimental branch)

**SuperBLT Log:**
[2023_02_19_log.txt](https://github.com/Crackdown-PD2/deathvox/files/10777192/2023_02_19_log.txt)

**Payday 2 Stack Trace:**
----------------------------------------------------------------------

Sun Feb 19 06:48:58 2023

Application has crashed: C++ exception
[string "lib/utils/listenerholder.lua"]:77: table index is nil

SCRIPT STACK

add() lib/utils/listenerholder.lua:9
add_destroy_listener() lib/units/unitbase.lua:15
_on_collision() @mods/deathvox-master/lua/lib/units/weapons/projectiles/arrowbase.lua:251
@mods/[deathvox-master/lua/lib/units/weapons/projectiles/arrowbase.lua:190
](https://github.com/Crackdown-PD2/deathvox/blob/daa8388e9be2ac489cfe1cd143f88d2fe5c9248b/lua/lib/units/weapons/projectiles/arrowbase.lua#L190)

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.135.169
	CPU : AMD Ryzen 7 3800X 8-Core Processor (8 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1
	DirectX : 12.0 
	GPU : Radeon (TM) RX 480 Graphics / aticfx32.dll[31.0.12027.2007]
	Language : english
	Memory :     31679MB 936KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek(R) Audio))

**Comment by offyerrocker** [comment]
This issue with Goodwill Hunting Aced is fixed in the Experimental build- however, if you're experiencing CTDs on map load, could you please tell me more about that? Which map were you playing? Can you please provide a crashlog?

**Comment by GenesisEB** [comment]
It crashes on loading ANY map. 

It was kind of hard to pin down what it was, turns out both of my weapons were triggering the same crash. 

Pistol Crossbow with Poison Bolts, and GL40 Grenade Launcher with Incendiary Rounds. 

Each weapon created the crash on its own. Removing the poison and incendiary modifications stopped the crash with both weapons equipped, so it looks like its being caused by special ammo mods on special weapons. Resetting the skill tree did not stop the crash so its probably not skill related.

**Experimental Stack Trace:**
----------------------------------------------------------------------
Application has crashed: C++ exception
[string "lib/units/weapons/newraycastweaponbase.lua"]:1073: attempt to perform arithmetic on field 'armor_piercing_add' (a boolean value)



SCRIPT STACK

_update_stats_values() @mods/base/req/core/Hooks.lua:262
_update_stats_values() lib/units/weapons/projectileweaponbase.lua:59
done_cb() lib/units/weapons/newraycastweaponbase.lua:407
clbk_part_unit_loaded() lib/managers/weaponfactorymanager.lua:909
assemble_from_blueprint() lib/managers/weaponfactorymanager.lua:657
assemble_from_blueprint() lib/units/weapons/newraycastweaponbase.lua:369
add_unit_by_factory_name() lib/units/beings/player/playerinventory.lua:405
original() lib/managers/playermanager.lua:825
_internal_load() @mods/base/req/core/Hooks.lua:262
spawned_player() lib/managers/playermanager.lua:1129
set_unit() lib/network/base/networkpeer.lua:2397
spawn_unit() lib/network/base/networkpeer.lua:2300
spawn_players() lib/network/base/basenetworksession.lua:1513
update() lib/states/ingamewaitingforplayers.lua:304
update() core/lib/utils/game_state_machine/coregamestatemachine.lua:92
original() lib/setups/setup.lua:916
update() @mods/base/req/core/Hooks.lua:262
update() lib/setups/gamesetup.lua:804
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:559


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     


-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.135.169
	CPU : AMD Ryzen 7 3800X 8-Core Processor (8 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1
	DirectX : 12.0 
	GPU : Radeon (TM) RX 480 Graphics / aticfx32.dll[31.0.12027.2007]
	Language : english
	Memory :     31679MB 936KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek(R) Audio))

**Comment by offyerrocker** [comment]
Thanks for the information- a fix is in progress. I'll update the thread when the fix is posted.

**Comment by offyerrocker** [comment]
This bug should be fixed now as of https://github.com/Crackdown-PD2/deathvox/commit/f76dceb9b27ec0f9bf06999509fe33eb96e2f01c , so make sure to update your copy of the experimental branch. Thanks for the thorough report information- please do open another issue if you encounter further bugs!
